version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

# services:
#   postgres:
#     image: postgres:16
#     container_name: library_postgres
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: library-service
#     ports:
#       - '5431:5432'
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - app-network

#   nestjs:
#     build: .
#     container_name: library_service
#     environment:
#       DATABASE_HOST: postgres
#       DATABASE_PORT: 5432
#       DATABASE_USER: postgres
#       DATABASE_PASSWORD: postgres
#       DATABASE_NAME: library-service
#     ports:
#       - '3000:3000'
#     depends_on:
#       - postgres
#     networks:
#       - app-network
#     # env_file:
#     #   - .env  # Load environment variables from the .env file in the current directory

#   pgadmin:
#     image: dpage/pgadmin4
#     restart: always
#     container_name: nest-pgadmin4
#     environment:
#       - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#       - PGADMIN_DEFAULT_PASSWORD=pgadmin4
#     ports:
#       - '5050:80'
#     depends_on:
#       - postgres

# networks:
#   app-network:
#     driver: bridge

# volumes:
#   postgres_data:
