# Use the official PostgreSQL image from the Docker Hub
FROM postgres:16

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=library-service

# Expose the PostgreSQL port
EXPOSE 5432
